// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpo7Lx-NKTWrVMTSzomNDJoVvh8adtyRs',
    appId: '1:907316484236:web:bacbf4ef6143bf72af83a9',
    messagingSenderId: '907316484236',
    projectId: 'roktobondhu-b1c11',
    authDomain: 'roktobondhu-b1c11.firebaseapp.com',
    storageBucket: 'roktobondhu-b1c11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApNPIR7R69QGnfjcfGhInaNk7nsuJE0IU',
    appId: '1:907316484236:android:af44cd55edf7606baf83a9',
    messagingSenderId: '907316484236',
    projectId: 'roktobondhu-b1c11',
    storageBucket: 'roktobondhu-b1c11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA1dZRHtDd8BPEQCpjf0g9GY-B_FKr1NU',
    appId: '1:907316484236:ios:1a701d50e60a5066af83a9',
    messagingSenderId: '907316484236',
    projectId: 'roktobondhu-b1c11',
    storageBucket: 'roktobondhu-b1c11.appspot.com',
    iosClientId: '907316484236-13h1rrh1l4roqul6hc79bec1darrk2lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.roktoBondhu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA1dZRHtDd8BPEQCpjf0g9GY-B_FKr1NU',
    appId: '1:907316484236:ios:1a701d50e60a5066af83a9',
    messagingSenderId: '907316484236',
    projectId: 'roktobondhu-b1c11',
    storageBucket: 'roktobondhu-b1c11.appspot.com',
    iosClientId: '907316484236-13h1rrh1l4roqul6hc79bec1darrk2lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.roktoBondhu',
  );
}
